version: "3"
services:
  crud_server:
    build: .
    container_name: crud_server
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=${DATABASE_URL_DOCKER}
      - PORT=3000
    depends_on:
      - postgres_db
    command: bash -c "npm run migrate:up && npm run seed && npm run start"

  postgres_db:
    image: postgres:13
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  postgres_data:
